### ISSUE TITLE
Issues with Historical Parameters

### ISSUE THREAD

**Issue by YuqiZ2020** [COVIDAnalytics/DELPHI#48]
Hi, 

Firstly thank you so much for producing this projection model and making all the code clear and transparent! 

I was trying to run the current V3 model today and I noticed that the program didn't go through the branch that utilizes historical parameter files, although I did provide the sample parameter file from 0718 that I got from your repo. I saw that the code for reading the past parameters was 

```
pastparameters = pd.read_csv(
            PATH_TO_FOLDER_DANGER_MAP + f"predicted/Parameters_Global_V2_{yesterday}.csv"
        )
```

but the historical parameter file that you provided was named ```Parameters_Global_V3_20200718.csv``` So I changed the 'V3' to 'V2' and got it working. Could you consider changing your code or changing the name of this sample parameter file? 

Also, does this mean the program would only utilize the parameters from yesterday but not previous days? Say that I only have the past parameter for 0718 alone but I want to run the program on 0720, does that mean the program can't utilize this past parameter? Will that cause any inaccuracy of the prediction?

Thank you in advance!

**Comment by MichaelLLi** [comment]
Hi Yuqi:

Thanks for the comment! We will update the name of the parameter file to fix this issue.

Yes, the program would only utilize the parameters from yesterday. At the end of the program, it would produce the parameter file for today. So if you use the past parameter for 0718 today, you should get a parameter file for 0719, which then you can use to run for 0720, and etc....

If you want to use past parameter for 0718 on 0720, just change the definition of the variable yesterday in the code depending on how many days you want to look back and it should work.

Best
-Michael Li

**Comment by YuqiZ2020** [comment]
Hi Michael, 

Sounds good, thank you for the clarification!

Best,
Yuqi
