### ISSUE TITLE
Unable to replicate the results

### ISSUE THREAD

**Issue by wayne315315** [COVIDAnalytics/DELPHI#66]
Dear COVIDAnalytics Team,
First, thanks for you excellent job on this project.

We are trying to replicate the results on provinces in Canada from DELPHI v3.0 (the latest commit on master branch).
We follow the instruction and execute the follow command on our terminal: (since it's the first run on Oct 22, it didn't use yesterday parameters)
python3 DELPHI_model_V3.py -u wayne -o tnc -ci 0 -s100 1 -w 0
python3 DELPHI_model_V3.py -u wayne -o trust-constr -ci 0 -s100 1 -w 0
python3 DELPHI_model_V3.py -u wayne -o annealing -ci 0 -s100 1 -w 0

All 3 results got similar output, but all the results we got have a huge 15-day MAPE error, and totally different from the prediction downloaded from your website https://www.covidanalytics.io/projections
In-Sample MAPE Last 15 Days ('Canada', 'Alberta'): 24.18 %
In-Sample MAPE Last 15 Days ('Canada', 'Manitoba'): 52.33 %
In-Sample MAPE Last 15 Days ('Canada', 'British Columbia'): 29.2 %

Can you give us some guidances on how to correctly execute the model ? (maybe using different branch other than master, or )
The DELPHI_output we got is on this [delphi_output](https://drive.google.com/drive/folders/1mqvdFto3OoHnFdqdDxq-bnYQ_L2b-35H?usp=sharing)
(including logs message & danger_map folders & diagrams showing discrepancy between prediction & true value we ran on)

We are looking forward to your reply. Thank you.

p.s. we also notice that only cases_cnt, death_cnt will really affect parameter estimation, maybe it's because the loss function for ODE parameter updating only consider these two fields ?

**Comment by MichaelLLi** [comment]
Hi Wayne, thanks for this. I believe the current difficulty is caused by the default initial bounds - they were decided a few months ago and intended to warm start the optimization at the start of the pandemic. It is not a good starting point at this stage anymore, and you should utilize a recent parameter file that we have. For reference, I have attached the latest file we have estimated yesterday.

[Parameters_Global_V2_20201022.zip](https://github.com/COVIDAnalytics/DELPHI/files/5430391/Parameters_Global_V2_20201022.zip)

**Comment by MichaelLLi** [comment]
You are correct in saying that only cases_cnt and death_cnt affect parameter estimation - we are closely monitoring the other data but we have still deemed recovery and hospitalization data to be unreliable at this stage to be utilized.

**Comment by wayne315315** [comment]
Hi Michael, 
Really appreciate your feedback ~ We'll run the code again with the updated file again tonight.
We'll let you know if the problem is solved or not ASAP.
Thanks again for your help

**Comment by MichaelLLi** [comment]
Hi Wayne, is the issue resolved? Thanks!

**Comment by wayne315315** [comment]
Hi michael,

sorry I didn't reply.
The issue is resolved. But the results on Hospitalization & ICU seems to be
way different than the actual numbers
Cases & Deaths have the similar trends as the ground truth, but a bit
deviation on the offset has been notice.

Best,
Wayne



Michael Lingzhi Li <notifications@github.com> 於 2020年11月9日 週一 上午6:26寫道：

**Comment by MichaelLLi** [comment]
The hospitalization and ICU numbers (along with recovery numbers) are not fitted to the data due to the fact that most countries have unreliable data

**Comment by MichaelLLi** [comment]
That would explain why hospitalization/icu data numbers are different - we are utilizing a global mean average prediction. And for where have you seen deviation in cases/deaths on ground truth? We are happy to investigate.
