### ISSUE TITLE
several bugs with Python scripts

### ISSUE THREAD

**Issue by afontenot** [COVIDAnalytics/DELPHI#8]
First of all, thank you for posting your model publicly. It's appreciated!

I've been attempting to replicate your results (out of personal interest, not because I have any reason to believe something is wrong). This has proven difficult for two reasons:

One issue is that the paths to data folders are hardcoded in the scripts, and these paths don't correspond to the actual location of the data in the Github repository. I managed to fix this, at least partially:

1. Change `PATH_TO_FOLDER_DANGER_MAP` and `PATH_TO_WEBSITE_PREDICTED` to "data/". 
2. Change `data_path` to "data_sandbox" in DELPHI_utils.py
3. Symlink `data/processed/Global` to `data/processed`.

(Note that the same folders appear to be hardcoded into the Mathamatica notebooks, so I expect the same issue to apply there. I haven't verified this, however.) This change may or may not be sufficient to fix the data folder location problem, because it was at this point that I ran into the other issue.

Other issue: path existence check is wrong here: https://github.com/COVIDAnalytics/DELPHI/blob/master/DELPHI_model.py#L44

You are looking for a file in the location 

    f"processed/Global/Cases_{country_sub}_{province_sub}.csv"

But, just two lines later, you are reading it from the real location:

    PATH_TO_FOLDER_DANGER_MAP + f"processed/Global/Cases_{country_sub}_{province_sub}.csv"

You should check that the path exists in the actual location that's being read from. Presumably this worked for you before because you had `processed/` in the same folder as the `model.py` and `PATH_TO_FOLDER_DANGER_MAP` was `"."`. In the Github repository, that folder is under `data/`.

The script hasn't yet finished running, and I haven't yet figured out how to parse the results, so it's possible I will run into other issues. I will either update this issue or file another one if I see other problems.

**Comment by hamzatazib** [comment]
Hello @afontenot 
Thank you for the feedback, and sorry for the inconvenience with the folder path naming: this must have been a nightmare. We are going to realse a new version where the path names are in a config.yml file, so you'll be able to add some keys to the dictionary with your username and should be able to run everything (and we'll make sure to release any data necessary to run any part of the code)
Regarding the path existence check, you are right and this is a bug in the version of the code that we've released quite a while ago. We should merge a newer version into master by end of next week and this bug will be fixed as well.
Thank you for your help :)

**Comment by hamzatazib** [comment]
We have added a config.yml file that makes the whole thing configurable for any new user as long as he/she updates that config.yml file as well as the USER_RUNNING variable at the beginning of all scripts. I hope this solves your issues @afontenot .
